language: php

env:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

before_install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - travis_retry composer install --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit

